name: list-pet
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - duckdb
  - streamlit
  - langchain
  - langchain-core
  - langchain-openai
  - tabulate
  - plotly
  - pandas
  - openai
  - python-dotenv
  - typer
  - pyyaml
  - minio
  - psycopg2
  - beautifulsoup4
  - pip
  - pip:
    - streamlit-autorefresh
